apiVersion: v1
kind: Service
metadata:
  name: classifier
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: classifier
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
